services:
  nginx:
    image: nginx:1.26.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./php/src:/usr/local/php-src
